### ISSUE TITLE
Add Rust Support

### ISSUE THREAD

**Issue by henryboisdequin** [benawad/stripcode#10]
I think it would be great for the Rust community if there was Rust support.

**Comment by benawad** [comment]
![image](https://user-images.githubusercontent.com/7872329/104815938-6fcc9700-57dd-11eb-8225-95bef45325a8.png)

**Comment by andys8** [comment]
@henryboisdequin Might be helpful: https://github.com/benawad/stripcode/pull/8#issuecomment-761594333

**Comment by henryboisdequin** [comment]
#12

**Comment by henryboisdequin** [comment]
#12
