### ISSUE TITLE
Super easy to misclick

### ISSUE THREAD

**Issue by elvinaspredkelis** [benawad/stripcode#3]
It shifts the answers down on new loaded code line. Selected the wrong answer a couple of times because of it.

Perhaps put the answer buttons at the top?

**Comment by dayvsonsales** [comment]
maybe a 2-sided layout is better for desktop version

**Comment by benawad** [comment]
I'm trying the answers on top right now

**Comment by theezeb** [comment]
If possible ``answers[left] code[right]``, so it's more visible with the strip down
right now, answers on top of the code, have to scroll a bit sometimes.
