### ISSUE TITLE
File doesn't give enough information

### ISSUE THREAD

**Issue by anirudh242** [benawad/stripcode#4]
Sometimes, some of the files don't give enough information to guess which repo it is. I just got this snippet.
![image](https://user-images.githubusercontent.com/73819495/104751069-e1bfc480-577a-11eb-8dd8-cd947e802940.png)
Maybe you could add some sort of requirement to add a snippet into the game.

**Comment by overlisted** [comment]
Look for `redacted`s and anything else that can help you, this game is very dumb
